"""'migrate_init'

Revision ID: 8c598534d93d
Revises: 
Create Date: 2022-07-05 11:20:42.258070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c598534d93d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('english', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.TEXT(length=50),
               nullable=True)
        batch_op.alter_column('translate',
               existing_type=sa.TEXT(length=50),
               nullable=True)
        batch_op.drop_index('english_translate')
        batch_op.drop_index('english_word')
        batch_op.create_unique_constraint('unique_word', ['word'])
        batch_op.create_unique_constraint('unique_translate', ['translate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('english', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('english_word', ['word'], unique=False)
        batch_op.create_index('english_translate', ['translate'], unique=False)
        batch_op.alter_column('translate',
               existing_type=sa.TEXT(length=50),
               nullable=False)
        batch_op.alter_column('word',
               existing_type=sa.TEXT(length=50),
               nullable=False)

    # ### end Alembic commands ###
